//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagTable
    {
        public string TagName { get; set; }
        public int id { get; set; }
        public string UserID { get; set; }
    }
}
