//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksTable
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
        public Nullable<bool> Priority { get; set; }
        public string Tag { get; set; }
        public int ID { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string UserId { get; set; }
    }
}
